apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml

components:
  - ../components/database-cnpg
  - ../components/networking
  - ../components/app-config

images:
  - name: ghcr.io/datum-cloud/backstage
