apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: backstage-postgres
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/component: database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: backstage
      owner: backstage
