apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
spec:
  template:
    spec:
      containers:
        - name: backstage
          args:
            - node
            - packages/backend
            - --config
            - app-config.yaml
            - --config
            - /etc/backstage/app-config.extra.yaml
          volumeMounts:
            - name: app-config
              mountPath: /etc/backstage
              readOnly: true
      volumes:
        - name: app-config
          configMap:
            name: backstage-app-config
